<!-- 

// Create table
$sql="CREATE TABLE books(name CHAR(50),author CHAR(30),book_id varchar(5),genre char(10),source varchar(200),blurb varchar(500))";

// Execute query
if (mysqli_query($con,$sql))
  {
  echo "Table user created successfully";
  }
else
  {
  echo "Error creating table: " . mysqli_error($con);
  }
?> 
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES ('The Power of Your Subconscious Mind','Dr. Joseph Murphy',1,'selfhelp','https://www.amazon.in/Power-Your-Subconscious-Mind-Success/dp/8172345666/ref=sr_1_1_sspa?keywords=books&qid=1553543764&refinements=p_72%3A1318476031&rnid=1318475031&s=gateway&sr=8-1-spons&psc=1','This remarkable book by Dr. Joseph Murphy, one of the pioneering voices of affirmative thinking, will unlock for you the truly staggering powers of your subconscious mind. Combining time-honored spiritual wisdom with cutting edge scientific research, Dr. Murphy explains how the subconscious mind influences every single thing that you do and how, by understanding it and learning to control its incredible force, you can improve the quality of your daily life.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Think and Grow Rich','Napoleon Hill','2','selfhelp','https://www.amazon.in/Think-Grow-Rich-Napoleon-Hill/dp/8192910911/ref=sr_1_3?s=books&ie=UTF8&qid=1553585295&sr=1-3&keywords=think+and+grow+rich','Think And Grow Rich has earned itself the reputation of being considered a textbook for actionable techniques that can help one get better at doing anything, not just by rich and wealthy, but also by people doing wonderful work in their respective fields. There are hundreds and thousands of successful people in the world who can vouch for the contents of this book. At the time of author’s death, about 20 million copies had already been sold. ');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Tao Te Ching','Lao Tsu','3','selfhelp','https://www.amazon.in/Tao-Te-Ching-Lao-Tzu/dp/9386538180/ref=sr_1_2_sspa?s=books&ie=UTF8&qid=1553585134&sr=1-2-spons&keywords=self+help+books+english+bestsellers&psc=1','From political advice and lessons on leading a balanced life to common practical wisdom and guidance on self-knowledge, humility, morality and virtue, this book gives an insight into the fundamental principles that form the basis of Taoism, one of the three great philosophical and religious traditions that originated in China.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('How to Win Friends and Influence People','Dale Carnegie','4','selfhelp','https://www.amazon.in/How-Win-Friends-Influence-People/dp/8192910997/ref=pd_bxgy_14_img_3/260-3654475-9578018?_encoding=UTF8&pd_rd_i=8192910997&pd_rd_r=bbc1e2fb-4f98-11e9-916b-9fe7fa64dd61&pd_rd_w=UR88z&pd_rd_wg=UxQxK&pf_rd_p=92c5dc59-6da4-488e-ba00-262537223f6b&pf_rd_r=TJ7F76ND8DNNR7P63N22&psc=1&refRID=TJ7F76ND8DNNR7P63N22','This is the book that gave birth to a self-improvement industry that spans the Globe (according to the Daily Express Newspaper). First written in 1936, this is the 2016 edition specially typeset for easy readability and offering terrific value for money. The book has sold over 32 million copies worldwide and has been translated into every major language. Still as vibrant and helpful as the day it was written it offers a simple set of guidelines. ');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Autopilot: The Art & Science of Doing Nothing',' Andrew Smart','5','selfhelp','https://www.amazon.in/dp/9386538067/ref=sspa_dk_detail_2?psc=1&smid=A3H3WE9M6NY1KV','Andrew Smart wants you to sit and do nothing much more often—and he has the science to explain why.At every turn, we’re pushed to do more faster, more efficiently: that drumbeat resounds throughout our wage-slave society. Multitasking is not only a virtue, it’s a necessity. But Autopilot argues that slackers may have the last laugh.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Right Behind You','Neil D'Silva','6','horror','https://www.amazon.in/Right-Behind-You-Neil-DSilva/dp/B077N6G1FP/ref=sr_1_1?s=books&ie=UTF8&qid=1553585828&sr=1-1&keywords=horror+books+in+english', 'Right Behind You is a collection of 13 horror stories of different genres. The thing that connects these stories is the emotion of our inner fears that resides in all of us. We might mask these fears, we might even deny them, but they emerge when least expected and then they begin to encroach upon every aspect of our lives. In this collection of assorted horror stories, you will find noir horror, urban myths, fantasies, campfire tales, stories of phobias, gore, and even a story that takes place entirely on chat.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Horsemen of Old',' Krishnarjun Bhattacharya','7','horror','https://www.amazon.in/dp/8175993766/ref=sspa_dk_detail_0?psc=1&smid=A3H3WE9M6NY1KV','‘There will come a time when it will talk to you.’‘The Darkness?’ ‘Yes. And when that time comes, do not answer.’');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Harappa - Curse of the Blood River','Vineet Bajpai','8','horror','https://www.amazon.in/Harappa-Curse-Blood-Vineet-Bajpai/dp/9352685482/ref=pd_sim_14_5/260-3654475-9578018?_encoding=UTF8&pd_rd_i=9352685482&pd_rd_r=5c283f75-4f9a-11e9-9bea-63c58c5cbb77&pd_rd_w=V8zqR&pd_rd_wg=AkmDT&pf_rd_p=3ba80840-2950-4d64-ba61-c68a14bd0939&pf_rd_r=1RVR97J72TV7TH88XBCN&psc=1&refRID=1RVR97J72TV7TH88XBCN','1700 BCE, Harappa – Harappa is a magnificent city on the banks of the mighty Saraswati river. The darkness of treachery, taantric exorcism and bloodshed unleashes itself on the last devta, paving the way for his devastating revenge…and the horrifying truth behind the fall of the glorious civilisation. 2017, Paris – The world’s most powerful religious institution is rattled. Europe’s dreaded crime lord meets a mysterious man in Paris. A lethal assassin boards a train, as Rome fears the worst. The prophesied devta has returned.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('The Curse of Mohenjodaro','The Curse of Mohenjodaro','9','horror','https://www.amazon.in/Curse-Mohenjodaro-Maha-Khan-Phillips/dp/9382616829/ref=pd_sim_14_3/260-3654475-9578018?_encoding=UTF8&pd_rd_i=9382616829&pd_rd_r=a80469a7-4f9a-11e9-98d0-c1ee69282464&pd_rd_w=eZ2i6&pd_rd_wg=SJPwN&pf_rd_p=3ba80840-2950-4d64-ba61-c68a14bd0939&pf_rd_r=P8VC2VNB21RT1MS86N51&psc=1&refRID=P8VC2VNB21RT1MS86N51','2016 AD. When footage of a team of archaeologists bursting into flames at the ancient site of Mohenjodaro goes viral, the world is horrified and shaken. While authorities suspect it to be an incendiary terrorist attack, Nadia Osbourne determines to find her archaeologist sister, Layla, convinced that she has survived. Her frantic search takes her to the ruins and forces her to confront her own demons – her inexplicable dreams about a woman named Jaya. 3800 BC. The city of Meluhha is on the brink of a revolution and Iaf and his coterie of corrupt priests will do anything to maintain their power. Jaya is the only one who can read the Bloodstone, the heart of the Goddess Shakari and divine the future. But with her daughter under Iaf’s control, will Jaya be able to prevent what is to come? Inspired by the legends surrounding the lost Indus Valley city, the Curse of Mohenjodaro is a gripping thriller about a powerful relic, a sinister cult and family secrets that haunt generations.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('The Green Room','Nag Mani','10','horror','https://www.amazon.in/Green-Room-Nag-Mani/dp/935206383X/ref=sr_1_2?s=books&ie=UTF8&qid=1553585828&sr=1-2&keywords=horror+books+in+english','"She wears an old uniform," Nisha continued, "pale white face, dark shadows around her eyes. She is often seen sitting on this very chair. And it is said that the chair is always found in front of the mirror no matter where you leave it." Rohan Agarwal has been appointed the manager of a play, and how excited he is to work with Chandni Joshi - his childhood crush, and unfortunately, his senior! A happy-go-lucky high school boarder, he has his fun with his friends, enjoys the odd sport and does not think twice before raiding his warden's office to leak question papers. Then, one misty night, he sneaks into the infamous Green Room; and there, he finds something that wasn't meant to be found... Mysterious happenings in the Green Room begin to follow. That's when Rohan stumbles on the fact that the same play was supposed to have taken place before, but it was cancelled. There was something evil associated with the play. Something terrible had happened in the Green Room the first time around, or at least, that's what the stories said. And yet, Rohan finds, the old stories turn out to be true. ');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('The Time Machine','H G Wells','mystery','11','https://www.amazon.in/Time-Machine-H-G-Wells/dp/8175992956/ref=sr_1_1_sspa?s=books&ie=UTF8&qid=1553587151&sr=1-1-spons&keywords=mystery+novels+bestseller&psc=1','A compelling science fiction, the Time Machine is a first-hand account of a Time Traveler's journey into the future. a pull of the lever and the machine sends him to the year 802,701, when humanity has split into two bizarre races—the ethereal Eloi and the subterranean Morlocks. Here, his machine is stolen and with the help of Weena, an Eloi he saved from drowning, the traveler is able to retrieve it.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Journey to the Centre of the Earth','Jules Verne','12','mystery','https://www.amazon.in/Journey-Centre-Earth-Jules-Verne/dp/8175994053/ref=pd_bxgy_14_img_2/260-3654475-9578018?_encoding=UTF8&pd_rd_i=8175994053&pd_rd_r=9ec4f0b8-4f9c-11e9-b697-d59d4673cb59&pd_rd_w=1pwh6&pd_rd_wg=GXhwC&pf_rd_p=92c5dc59-6da4-488e-ba00-262537223f6b&pf_rd_r=21KFB753EWG6WYQ90GMJ&psc=1&refRID=21KFB753EWG6WYQ90GMJ','Professor Liedenbrock, a man of incredible impatience and Axel, his unadventurous nephew, come across a coded note in an original runic manuscript of an Icelandic saga. as they try to decipher the code and reveal the message, the results are not quite meaningful.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Treasure Island','Robert Louis Stevenson','13','mystery','https://www.amazon.in/Treasure-Island-Robert-Louis-Stevenson/dp/8172344767/ref=pd_sim_14_4/260-3654475-9578018?_encoding=UTF8&pd_rd_i=8172344767&pd_rd_r=a5a5590a-4f9c-11e9-b1b6-3b091b3644fc&pd_rd_w=S7rOW&pd_rd_wg=OMGPU&pf_rd_p=3ba80840-2950-4d64-ba61-c68a14bd0939&pf_rd_r=G2SKXKVH7A7P05C8HXBM&psc=1&refRID=G2SKXKVH7A7P05C8HXBM','Think of the high seas and of a buccaneer ship; of a wild seaman with a sea chest full of gold; of Long John Silver; of a buried treasure and of young Jim Hawkins, the boy with the treasure map the key to it all. ');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('King of Scars','Leigh Bardugo','14','mystery','https://www.amazon.in/dp/1510105662/ref=sspa_dk_detail_3?psc=1','The much-anticipated first book in a brand-new duology by New York Times bestselling author, Leigh Bardugo.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('The Priory of the Orange Tree','Samantha Shannon','15','mystery','https://www.amazon.in/Priory-Orange-Tree-Samantha-Shannon/dp/1526612860/ref=pd_cp_14_4/260-3654475-9578018?_encoding=UTF8&pd_rd_i=1526612860&pd_rd_r=0cc3a955-4f9d-11e9-922d-ddd022652761&pd_rd_w=KJOSg&pd_rd_wg=Mp0Cq&pf_rd_p=cf49abc6-2d3e-4a22-9a85-f5ff7f5942fa&pf_rd_r=MWY3QTAF0C90G91GEKQY&psc=1&refRID=MWY3QTAF0C90G91GEKQY','From the internationally bestselling author of the bone season, a trailblazing, epic high fantasy about a world on the brink of war with dragons – and the women who must lead the fight to save it. A world divided. A queendom without an heir. An ancient enemy awakens. The house of berethnet has ruled inys for a thousand years. Still unwed, queen SA br An the ninth must conceive a daughter to protect her realm from destruction – but assassins are getting closer to her door. Ead duryan is an outsider at Court. Though she has risen to the position of lady-in- waiting, she is loyal to a hidden society of mages. Ead keeps a watchful eye on SA br An, secretly protecting her with forbidden magic. Across the dark sea, tané has trained to be a dragonrider since she was a child, but is forced to make a choice that could see her life unravel. Meanwhile, the divided East and West refuse to parley, and forces of chaos are rising from their sleep.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('The Winter of the Witch: The Winternight Trilogy','Katherine Arden','16','fantasy','https://www.amazon.in/Winter-Witch-Winternight-Trilogy/dp/1785039717/ref=pd_bxgy_14_img_3/260-3654475-9578018?_encoding=UTF8&pd_rd_i=1785039717&pd_rd_r=6b1e538b-4f9d-11e9-971f-cf23f04e52da&pd_rd_w=xVfxm&pd_rd_wg=eX1NK&pf_rd_p=92c5dc59-6da4-488e-ba00-262537223f6b&pf_rd_r=F1ZW15HEBVH5PFFNJDAQ&psc=1&refRID=F1ZW15HEBVH5PFFNJDAQ','One girl can make a difference. Moscow is in flames, leaving its people searching for answers and someone to blame. Vasilisa, a girl with extraordinary gifts, must flee for her life, pursued by those who blame their misfortune on her magic. Then a vengeful demon, stronger than ever. Determined to engulf the world in chaos, he finds allies among men and spirits. Mankind and magical creatures alike find their fates resting on Vasya's shoulders. But she may not be able to save them all.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Red Glove (The Curse Workers)','Holly Black','17','fantasy','https://www.amazon.in/dp/1442403403/ref=sspa_dk_detail_3?psc=1','After rescuing his brothers from Zacharov’s retribution and finding out that Lila, the girl he has loved his whole life, will never, ever be his, Cassel is trying to reestablish some kind of normalcy in his life. That was never going to be easy for someone from a worker family that’s tied to one of the big crime families—and whose mother’s cons get more reckless by the day. But Cassel is coming to terms with what it means to be a transformation worker, and he’s figuring out how to have friends. Except normal doesn’t last very long. Soon Cassel is being courted by both sides of the law and is forced to confront his past—a past he remembers only in scattered fragments, and one that could destroy his family and his future. Cassel will have to decide whose side he wants to be on, because neutrality is not an option. And then he will have to pull off his biggest con ever to survive.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Fantastic Beasts: The Crimes of Grindelwald: The Original Screenplay','J K Rowling','18','https://www.amazon.in/gp/product/1408711702/ref=s9_acsd_zwish_hd_bw_b1RCYeF_c_x_w?pf_rd_m=A1K21FY43GMZF8&pf_rd_s=merchandised-search-11&pf_rd_r=5MBT1R1VH8G14QHW81Q6&pf_rd_t=101&pf_rd_p=4abe71a6-e289-5da6-a733-3c35489314e6&pf_rd_i=1318087031','At the end of Fantastic Beasts and Where to Find Them, the powerful Dark wizard Gellert Grindelwald was captured in New York with the help of Newt Scamander. But, making good on his threat, Grindelwald escapes custody and sets about gathering followers, most unsuspecting of his true agenda: to raise pure-blood wizards up to rule over all nonmagical beings.');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('Fantastic Beasts and Where to Find Them','J K Rowling','19','fantasy','https://www.amazon.in/Fantastic-Beasts-Where-Find-Them/dp/1408708981/ref=pd_bxgy_14_img_2/260-3654475-9578018?_encoding=UTF8&pd_rd_i=1408708981&pd_rd_r=eb54f0a4-4f9e-11e9-8eea-cd30334cc585&pd_rd_w=WUPlq&pd_rd_wg=CWhu9&pf_rd_p=92c5dc59-6da4-488e-ba00-262537223f6b&pf_rd_r=SZAHDH4MF2MHN6QVNH4D&psc=1&refRID=SZAHDH4MF2MHN6QVNH4D','J.K. Rowling is the author of the bestselling Harry Potter series of seven books, published between 1997 and 2007, which have sold over 450 million copies worldwide, are distributed in more than 200 territories, translated into 74 languages, and have been turned into eight blockbuster films. She has also written two small volumes, which appear as the titles of Harry's schoolbooks within the novels. Fantastic Beasts and Where to Find Them and Quidditch Through The Ages were published by Bloomsbury Children's Books in March 2001 in aid of Comic Relief. In December 2008, The Tales of Beedle the Bard was published in aid of the Children's High Level Group, and quickly became the fastest selling book of the year ');
mysqli_query($link,"INSERT INTO books(name, author, book_id, genre, source,blurb)
VALUES('The Palace of Illusions',' Chitra Banerjee Divakaruni','20','fantasy','https://www.amazon.in/dp/9386215667/ref=sspa_dk_detail_2?psc=1&smid=A2KMDR5XHLB83B','Chitra Banerjee Divakaruni’s books include the bestselling novels The Mistress of Spices (longlisted for the Orange Prize), Queen of Dreams and Sister of My Heart, the prizewinning story collections Arranged Marriage and The Unknown Errors of Our Lives, and the ‘Conch Bearer’ series for children. She teaches creative writing at the University of Houston.'); -->
